### ISSUE TITLE
ボタンの処理をどうすれば良いのかわかりません。

### ISSUE THREAD

**Issue by miouemura** [miouemura/typing_game#4]
最初はボタン（文字入り）が表示してあるけれど、そのあとは使わないため、途中から消したいんですけど、どうすれば良いですか？

**Comment by teramotodaiki** [comment]
@miouemura 
ボタン（element）を消したいときは、ボタンに対して `element.parentNode.removeChild(element)` を実行すれば消せるよ

c.f. https://developer.mozilla.org/ja/docs/Web/API/Node/removeChild

**Comment by miouemura** [comment]
ありがとうございました。

**Comment by miouemura** [comment]
その後、お母さんの友達の大学生のお兄さん達とYahooのHACK Uというイベントに出ました。

https://hacku.yahoo.co.jp/hacku2019tokyo/ <https://hacku.yahoo.co.jp/hacku2019tokyo/>

発表資料はこちらです


教えていただいてありがとうございました

植村実央
